### PR TITLE
Add collectgarbage() calls in thread

### PR DESCRIPTION
**Pull request by karandwivedi42**
Ref: https://github.com/torchnet/torchnet/issues/39

### CODE REVIEW

**Comment by lvdmaaten** [comment]
Hmmm now that I think of it: I do have one concern with this change: you're now doing gc in the main thread after every sample, which will slow down things substantially. I think it is better to add something like `if (idx % 1000) == 0 then ... end` around the gc calls.

Also, I presume `DatasetIterator` requires a similar change?

**Comment by colesbury** [comment]
DatasetIterator probably doesn't need one because the issue is specific to threads -- it's hard to determine which thread needs an automatic GC with shared tensors.

One collectgarbage() is enough. (Try running with only one collectgarbage; I suspect the memory usage is the same as with two). People do two collectgarbage so that the Lua object is collected -- but the Lua objects here are very lightweight, it's the TH managed tensor data that's heavy that you care about.

**Comment by karandwivedi42** [comment]
@colesbury yes, there is not much difference in memory usage when keeping 1 or 2 calls.

@lvdmaaten Surprisingly, there is a speedup instead of slow down after adding the gc calls. I cannot justify but tried with fb.resnet type data loading and consistently there is a speedup with the function calls. Adding gc function call immediately after image.load() (more aggressive) does slow down data loading a lot though.

**Comment by karandwivedi42** [comment]
My memory issue solved without this change. So, I am closing the PR

**Pull request closed without merging**
