### PR TITLE
New TableMeter

### PR DESCRIPTION
**Pull request by gforge**
I've been using the `nn.ConcatTable` for my networks and it outputs a table that is incompatible with current Meters. The proposed `TableMeter` in this PR takes an output that is in table format and then forwards each element to the corresponding meter.

I've added rudimentary tests for the `TableMeter`. The current test are primarily intended for testing the `TableMeter` but I also added the `AverageValueMeter` in the progress. 

I've checked the code using the luacheck linter. There is a little odd solution workaround for the table.unpack() [5.2 incompatibility](https://www.corsix.org/content/look-lua-52-work3). In the torch-dataframe we've [solved this](https://github.com/AlexMili/torch-dataframe/blob/develop/utils.lua#L230-L232) by assigning `unpack` to `table.unpack` and only using the latter. If all the `__init` have the `noordered = true` then this could be skipped entirely.

### CODE REVIEW

**Comment by lvdmaaten** [comment]
The unit tests for the meters are highly appreciated!

I am not sure I understand the need for a `TableMeter` though. Really all this is a container for a bunch of meters. Isn't it trivial to store all meters in a Lua table? 

```
local meters = {tnt.ClassErrorMeter{top = {1}}, tnt.mAPMeter()}
-- start of training loop...
for _,meter in ipairs(meters) do meter:add(state.network.output, state.sample.target) end
-- end of training loop...
for _,meter in ipairs(meters) do print(torch.typename(meter), meter:value()) end
```

I am worried the `TableMeter` will lead to confusion for two reasons: (1) as opposed to all other meters, it doesn't actually measure anything but is just a container; and (2) it assumes that all the meters in the `TableMeter` receive the same input, which is untrue: for instance, if I stick a `TimeMeter` and a `ClassErrorMeter` in the `TableMeter` (which I'm sure people will try to do), the current code will fail. But perhaps I'm missing an important use case for `TableMeter`?

**Comment by gforge** [comment]
I agree, there is a difference between the other meters and the TableMeter. The detail that you've missed is that it splits the `output` and `target` into each meter in a way that reflects the `ConcatTable`, e.g. `meter_1:add(state.network.output[1], state.sample.target[1])`, `meter_2:add(state.network.output[2], state.sample.target[2])`. It does make my life easier but I do see that it makes sense to perhaps leave this functionality to an [addon-package](https://github.com/gforge/torchnet-addons). The name should also perhaps be `ConcatMeter`, strengthening the connection to the `nn.ConcatTable` class.

As it's a specific `output` & `target` oriented Meter it makes no sense in using it for a `TimeMeter` although I can certainly seen your point about people will try to put anything into it. I did a slight modification in [another version](https://github.com/gforge/torchnet-addons/blob/master/meter/tablemeter.lua) with a [check](https://github.com/gforge/torchnet-addons/blob/master/meter/tablemeter.lua#L26) that the supplied meted has the `add`, `value` meters that the class expects. I've thought of adding multiple meters and coupling them to specific outputs, this certainly makes sense if there is both a classification target and a regression target. 

Glad you liked the tests, I can see if I have time to add a few more for the remaining meters. I must though say that the torch tester feels outdated after having used  [busted](http://olivinelabs.com/busted/) for a while. Also the loading solution for the package requires the entire package to be installed before testing (unless I've missed something), this makes test-driven development a little harder and since you only have lua-files you should probably be able to load them all via simple `loadfile` calls whilst passing the `tnt` table in the function call. Otherwise your solution is elegant and I'm amazed of the code quality - everything that I've suspected to be a bug has turned out to be my incomplete understanding of the language.

**Comment by lvdmaaten** [comment]
Yeah, I think this is too specific for the core of torchnet; it would be better to have it in some subpackage.

The tests are still very welcome though! It would be nice to get a good coverage here. I'm not very familiar with the inner workings of LuaRocks, but can't you edit the Lua-files directly in the locations where LuaRocks installs them if you want to do test-driven development?

**Comment by gforge** [comment]
No problem. I'll try to add some test-cases, I need to familiarise myself with the meters available. Do you want me to add an issue for this? 

Regarding true coverage reporting I don't think the torch testSuite has that functionality. We solved that in the [torch-dataframe](https://github.com/AlexMili/torch-dataframe/tree/develop) using a [script for running the busted specs](https://github.com/AlexMili/torch-dataframe/blob/develop/specs/run_all.sh) and a [second script for the luacov](https://github.com/AlexMili/torch-dataframe/blob/develop/specs/coverage.sh). 

You are right about the ability to install the package from a local directory using `luarocks make <rockspec>`. I just found it useful that the init file loads everything based on the current directory it's in, this allows me to change files and develop the package without installing and affecting other parts of the system. I haven't worked with anything compiled though and this could potentially change how this approach works.

**Comment by lvdmaaten** [comment]
Thanks!

**Pull request merged**
