### PR TITLE
Normalize MNIST data by 256

### PR DESCRIPTION
**Pull request by szagoruyko**
Better accuracy!

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by ebetica** [comment]
Hey Sergey, can you resend an email to cla@fb.com with your info? I'm not sure why we don't have your CLA anymore, but we can merge this PR once you do. Sorry about that!

**Comment by szagoruyko** [comment]
thanks @ebetica I contacted them a while ago, should we try to merge it again? I have a couple of other PRs to add

**Comment by ebetica** [comment]
Looks like we still don't have your CLA on file... Did you try contacting them after my October message? If so I'll ask the Open Source team to look into your email.

**Comment by szagoruyko** [comment]
@ebetica I sent the sighned CLA a few weeks ago.

**Pull request merged**
