### PR TITLE
Fix doc for running example

### PR DESCRIPTION
**Pull request by Atcold**
Fix missing reference to installation of `mnist` package.

### CODE REVIEW

**Comment by lvdmaaten** [comment]
These changes are not going to survive re-generation of the documentation unless you make them here as well: https://github.com/torchnet/torchnet/blob/master/init.lua#L45

**Comment by Atcold** [comment]
@lvdmaaten: I've checked that file, and there are no reference to the example whatsoever.
So, I'm a little puzzled. How has this documentation been made?

**Comment by Atcold** [comment]
This comes from the file you pointed out
```
Assuming *torch* is already installed, the *torchnet* core is only a set of
lua files, so it is straightforward to install it with *luarocks*
```
luarocks install torchnet
```
## Documentation
Requiring *torchnet* returns a local variable containing all *torchnet*
class constructors.
```

**Comment by lvdmaaten** [comment]
It was (erroneously!) added manually to `README.md`. The entire example bit of the documentation should go into the comments in `init.lua`.

**Comment by Atcold** [comment]
Fixing it all now, then. Force-pushing soon.

**Comment by Atcold** [comment]
Done.
I'm not sure what's happened with this last commit. It says we've commit together... which is something I've never seen before. Moreover, in my PR some files I've not touched have been modified.
What's going on?

I've updated the `init.lua`.

**Comment by Atcold** [comment]
Hold on, I'm doing a mess...

**Comment by Atcold** [comment]
Done.

**Comment by lvdmaaten** [comment]
Thanks!

**Comment by Atcold** [comment]
@lvdmaaten, I wrote you on Gitter. Could you have a look at it, please?

**Pull request merged**
